### PR TITLE
Add fallback to distutils

### PR DESCRIPTION
**Pull request by cooperlees**
- This is so we can build this in an environment that does not yet have
  setuptools
- Also added Python 3.6 as I built this with 3.6

### CODE REVIEW

**Comment by cooperlees** [comment]
Maybe time to also add 3.6 to travis 👌🏻

**Comment by adamjstewart** [comment]
Mostly a duplicate of #84. One of these two PRs should definitely be merged though.

**Comment by jaraco** [comment]
Although this workaround might help alleviate the issue, pip will still always attempt to build sdists with setuptools... so it may not help.

**Comment by adamjstewart** [comment]
> pip will still always attempt to build sdists with setuptools

By attempt, do you mean that it will try to install `setuptools` from source first? If it uses a wheel, then that wouldn't be a problem. If it doesn't try to build `setuptools` from source, then wouldn't the fallback of distutils work?

P.S. I know next to nothing about pip and sdists, so I could be very mistaken.

**Comment by jaraco** [comment]
I mean it will [uncoditionally](https://github.com/pypa/pip/blob/master/pip/utils/setuptools_build.py#L3) `import setuptools` when building any sdist, which it will do in a subprocess of the current Python environment in whatever package state it happens to be in.

**Comment by cooperlees** [comment]
Why it may not help pip directly it will help people who run setup.py manually (with other automation) building from sdsts.

**Comment by zoofood** [comment]
Thanks Cooper. I'll bring it up to Python 3.6 as well. I used an earlier PR with the same fix. I hope this helps you out.

**Pull request closed without merging**
