### PR TITLE
Remove unnecessary use of pywin32 for loading Windows folder

### PR DESCRIPTION
**Pull request by ofek**
Another attempt at https://github.com/ActiveState/appdirs/pull/118 cc @pradyunsg

Closes https://github.com/ActiveState/appdirs/pull/107 (I ran into something similar)
Closes https://github.com/ActiveState/appdirs/issues/108

It's unclear who's maintaining this so cc @zoofood @daved @rawktron @MDrakos @Naatan @autarch @jdufresne 

Could we also get a release? I saw https://github.com/ActiveState/appdirs/issues/79, indicating this library may not be getting the love it deserves. That is quite unfortunate since many projects rely on `appdirs`:

```
ofek@ozone ~\Desktop $ pypinfo --days 365 appdirs
Served from cache: False
Data processed: 638.08 GiB
Data billed: 638.08 GiB
Estimated cost: $3.12

| download_count |
| -------------- |
|     39,354,264 |
```

### CODE REVIEW

**Comment by McSinyx** [comment]
Since you're touching these, can you also refactor the try-except to try-except-else to be more explicit?

**Comment by ofek** [comment]
@McSinyx Done!

**Comment by ofek** [comment]
Any update?

**Comment by ofek** [comment]
Bump

also cc @mdrohmann

**Comment by ofek** [comment]
Has there been any progress here?

**Comment by ofek** [comment]
Any news?

**Comment by pradyunsg** [comment]
Nudging on this PR for reviews/merge.

**Comment by ofek** [comment]
cc @zoofood

**Comment by pradyunsg** [comment]
*sigh*

**Comment by zoofood** [comment]
LGTM. Thanks for the contribution. Nice to remove pywin32. Also kudos to @pradyunsg who previously contributed as well on this.

**Comment by ofek** [comment]
@zoofood Can this be released?

**Comment by zoofood** [comment]
Hi @ofek, working on the next release here. Working through the backlog of changes, won't all go out in one big bang (not how I like to release items.  It's coming!

**Comment by ofek** [comment]
Yay!!!

**Comment by ofek** [comment]
Soon? 🙂

**Comment by ofek** [comment]
?

**Comment by ofek** [comment]
Any update?

**Pull request merged**
